version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      - "MYSQL_DATABASE=cadb"
      - "MYSQL_ROOT_PASSWORD=r00t"