CREATE DATABASE IF NOT EXISTS cadb;
USE cadb;
CREATE TABLE IF NOT EXISTS todo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task TEXT,
    completed TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;
CREATE INDEX idx_tdtask
ON todo (id, task);